import { useMemo, useState, type ReactNode } from 'react'
import { Activity, BarChart3, Calculator, ClipboardCheck, DatabaseZap, FlaskConical, Gauge, PackageCheck, Scale, Store, Target } from 'lucide-react'
import type { BreakdownRow,Lang,SeriesPoint } from './types'

const compact=(value:number,lang:Lang)=>new Intl.NumberFormat(lang==='pt'?'pt-BR':'en-US',{notation:'compact',maximumFractionDigits:1}).format(Number.isFinite(value)?value:0)
const pct=(value:number)=>`${(100*(Number.isFinite(value)?value:0)).toFixed(1)}%`
const num=(row:Record<string,string|number>,key:string)=>Number(row[key]??0)

export type ForecastEvaluation={holdout_observations?:number;candidate_improvement?:number;selected_model?:string;baseline?:Record<string,number|string>;candidate?:Record<string,number|string>}
export function seriesStats(rows:SeriesPoint[]){const values=rows.map(row=>Number(row.value)).filter(Number.isFinite);if(!values.length)return{mean:0,cv:0,first:0,last:0,change:0,points:0};const mean=values.reduce((s,v)=>s+v,0)/values.length,sd=Math.sqrt(values.reduce((s,v)=>s+(v-mean)**2,0)/values.length),first=values[0],last=values.at(-1)??0;return{mean,cv:mean?sd/mean:0,first,last,change:first?(last-first)/first:0,points:values.length}}
export function changeDrivers(rows:BreakdownRow[]){return rows.filter(row=>row.previous!==undefined).map(row=>({...row,change:row.value-(row.previous??0)})).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change))}
export function concentration(rows:BreakdownRow[],total:number){const ranked=[...rows].sort((a,b)=>b.value-a.value);return{leader:ranked[0],top3Share:total?ranked.slice(0,3).reduce((s,r)=>s+r.value,0)/total:0}}

function Stat({value,children,tone}:{value:string;children:ReactNode;tone?:'positive'|'negative'}){return <article><strong className={tone}>{value}</strong><span>{children}</span></article>}
function DriverList({rows,lang,inverse=false}:{rows:ReturnType<typeof changeDrivers>;lang:Lang;inverse?:boolean}){const shown=rows.slice(0,4),max=Math.max(...shown.map(row=>Math.abs(row.change)),1);return <div className="ops-driver-list">{shown.map(row=>{const positive=inverse?row.change<=0:row.change>=0;return <div key={row.name}><span>{row.name}</span><i><b style={{width:`${100*Math.abs(row.change)/max}%`}}/></i><strong className={positive?'positive':'negative'}>{row.change>=0?'▲':'▼'} {compact(Math.abs(row.change),lang)}</strong></div>})}</div>}

type OpsLens='priority'|'coverage'|'drivers'|'volatility'|'scenario'
function OpsCommand({values,trend,breakdown,detail,lang}:{values:Record<string,number>;trend:SeriesPoint[];breakdown:BreakdownRow[];detail:Record<string,string|number>[];lang:Lang}){
 const[lens,setLens]=useState<OpsLens>('priority'),[demand,setDemand]=useState(100)
 const critical=detail.filter(r=>String(r.risk_status).match(/Critical|Out of stock/)).length,out=detail.filter(r=>String(r.risk_status)==='Out of stock').length,onHand=detail.reduce((s,r)=>s+num(r,'on_hand'),0),target=detail.reduce((s,r)=>s+num(r,'target_stock'),0),avgDaily=detail.reduce((s,r)=>s+num(r,'avg_daily_demand'),0),stats=seriesStats(trend),drivers=changeDrivers(breakdown),recommended=Math.max(0,Math.round(avgDaily*12*(demand/100)-onHand))
 const tabs:[OpsLens,string,typeof Target][]=[['priority',lang==='pt'?'Prioridade':'Priority',ClipboardCheck],['coverage',lang==='pt'?'Cobertura':'Coverage',Gauge],['drivers',lang==='pt'?'Drivers':'Drivers',BarChart3],['volatility',lang==='pt'?'Variabilidade':'Variability',Activity],['scenario',lang==='pt'?'Cenário':'Scenario',FlaskConical]]
 return <section className="ops-lab"><div className="ops-lab-head"><div><span>{lang==='pt'?'LABORATÓRIO OPERACIONAL · REGRAS EXPLÍCITAS':'OPERATIONS LAB · EXPLICIT RULES'}</span><h2>{lang==='pt'?'Cinco lentes para priorizar estoque':'Five lenses for inventory priorities'}</h2></div><div role="tablist">{tabs.map(([id,label,Icon])=><button role="tab" aria-selected={lens===id} className={lens===id?'active':''} onClick={()=>setLens(id)} key={id}><Icon/>{label}</button>)}</div></div><div className="ops-lab-body">
  {lens==='priority'&&<><div className="ops-copy"><b>{lang==='pt'?'O que precisa de dono hoje':'What needs an owner today'}</b><p>{lang==='pt'?'Fila ordenada por severidade e necessidade de reposição.':'Queue ordered by severity and replenishment need.'}</p></div><Stat value={compact(values.risk||critical,lang)}>{lang==='pt'?'posições em risco':'positions at risk'}</Stat><Stat value={String(critical)} tone={critical?'negative':undefined}>{lang==='pt'?'itens críticos visíveis':'critical items visible'}</Stat><Stat value={compact(values.reorder||0,lang)}>{lang==='pt'?'unidades sugeridas':'suggested units'}</Stat></>}
  {lens==='coverage'&&<><div className="ops-copy"><b>{lang==='pt'?'Estoque atual cobre o alvo?':'Does current stock cover target?'}</b><p>{lang==='pt'?'Snapshot atual; não é comparação temporal.':'Current snapshot; not a time comparison.'}</p></div><Stat value={pct(target?onHand/target:0)}>{lang==='pt'?'estoque versus alvo':'stock versus target'}</Stat><Stat value={String(out)} tone={out?'negative':undefined}>{lang==='pt'?'rupturas visíveis':'visible stockouts'}</Stat><Stat value={compact(Math.max(0,target-onHand),lang)}>{lang==='pt'?'gap até o alvo':'gap to target'}</Stat></>}
  {lens==='drivers'&&<><div className="ops-copy"><b>{lang==='pt'?'Quais divisões moveram vendas?':'Which divisions moved sales?'}</b><p>{lang==='pt'?'Variação absoluta de vendas contra a janela anterior.':'Absolute sales change versus the prior window.'}</p></div><DriverList rows={drivers} lang={lang}/></>}
  {lens==='volatility'&&<><div className="ops-copy"><b>{lang==='pt'?'Vendas estáveis ou irregulares?':'Stable or irregular sales?'}</b><p>{lang==='pt'?'Coeficiente de variação sobre a série diária filtrada.':'Coefficient of variation over the filtered daily series.'}</p></div><Stat value={pct(stats.cv)}>{lang==='pt'?'variabilidade relativa':'relative variability'}</Stat><Stat value={compact(stats.mean,lang)}>{lang==='pt'?'média diária':'daily average'}</Stat><Stat value={pct(stats.change)} tone={stats.change>=0?'positive':'negative'}>{lang==='pt'?'primeiro ao último dia':'first to last day'}</Stat></>}
  {lens==='scenario'&&<><div className="ops-copy"><b>{lang==='pt'?'E se a demanda mudar?':'What if demand changes?'}</b><p>{lang==='pt'?'Sensibilidade linear de 12 dias; não é ordem de compra.':'Linear 12-day sensitivity; not a purchase order.'}</p></div><label><span>{lang==='pt'?'Demanda':'Demand'} <b>{demand}%</b></span><input type="range" min="70" max="140" value={demand} onChange={e=>setDemand(Number(e.target.value))}/></label><Stat value={compact(recommended,lang)}>{lang==='pt'?'unidades simuladas':'simulated units'}</Stat><Stat value={compact(avgDaily,lang)}>{lang==='pt'?'demanda diária visível':'visible daily demand'}</Stat></>}
 </div></section>
}

type Lens=0|1|2|3|4
const copy:Record<string,{title:[string,string];tabs:[string,string][];questions:[string,string][]}>={
 forecast:{title:['Five lenses for forecast decisions','Cinco lentes para decisões de previsão'],tabs:[['Backtest','Backtest'],['Error','Erro'],['Bias','Viés'],['Demand stability','Estabilidade'],['Demand scenario','Cenário']],questions:[['Did the candidate beat the baseline?','O candidato superou o baseline?'],['How large is forecast error?','Qual é o tamanho do erro?'],['Does the model systematically over or under forecast?','O modelo superestima ou subestima?'],['Is demand stable enough to plan?','A demanda é estável o suficiente?'],['What if observed demand changes?','E se a demanda observada mudar?']]},
 risk:{title:['Five lenses for inventory risk','Cinco lentes para risco de estoque'],tabs:[['Severity','Severidade'],['Stock gap','Gap de estoque'],['Demand drivers','Drivers'],['Exposure','Exposição'],['Stress test','Teste de estresse']],questions:[['What must be resolved first?','O que deve ser resolvido primeiro?'],['How far is stock from target?','Qual é o gap até o alvo?'],['Which groups carry demand exposure?','Quais grupos concentram demanda?'],['Is exposure concentrated?','A exposição está concentrada?'],['What if demand rises?','E se a demanda subir?']]},
 explorer:{title:['Five lenses for network comparison','Cinco lentes para comparar a rede'],tabs:[['Contribution','Contribuição'],['Change drivers','Mudanças'],['Performance gap','Gap'],['Concentration','Concentração'],['Rebalance','Rebalanceamento']],questions:[['Who contributes most?','Quem mais contribui?'],['Who changed most?','Quem mais mudou?'],['How wide is the network gap?','Qual é a distância da rede?'],['Does sales depend on few groups?','As vendas dependem de poucos grupos?'],['What if leader volume is redistributed?','E se parte do líder for redistribuída?']]},
 replenishment:{title:['Five lenses for replenishment','Cinco lentes para reposição'],tabs:[['Need','Necessidade'],['Lead time','Prazo'],['Safety stock','Segurança'],['Demand','Demanda'],['Recommendation','Recomendação']],questions:[['What needs replenishment?','O que precisa de reposição?'],['How does lead time change need?','Como o prazo altera a necessidade?'],['What buffer is required?','Qual proteção é necessária?'],['How sensitive is the plan to demand?','Quanto o plano depende da demanda?'],['What is the transparent recommendation?','Qual é a recomendação transparente?']]},
 trust:{title:['Five lenses for data trust','Cinco lentes para confiança dos dados'],tabs:[['Completeness','Completude'],['Coverage','Cobertura'],['Integrity','Integridade'],['Reconciliation','Reconciliação'],['Readiness','Prontidão']],questions:[['Did required checks pass?','Os testes necessários passaram?'],['How much history supports the view?','Quanto histórico sustenta a visão?'],['Are grains and fields defensible?','Grãos e campos são defensáveis?'],['What totals can be reconciled?','Quais totais podem ser reconciliados?'],['Can this output guide action?','Esta saída pode orientar ação?']]}
}

function PlanningPageLab({pageId,values,trend,breakdown,detail,forecast,lang}:{pageId:string;values:Record<string,number>;trend:SeriesPoint[];breakdown:BreakdownRow[];detail:Record<string,string|number>[];forecast?:ForecastEvaluation;lang:Lang}){
 const[lens,setLens]=useState<Lens>(0),[scenario,setScenario]=useState(110),[lead,setLead]=useState(7),[safety,setSafety]=useState(5)
 const c=copy[pageId]??copy.trust,stats=seriesStats(trend),drivers=changeDrivers(breakdown),ranked=[...breakdown].sort((a,b)=>b.value-a.value),conc=concentration(breakdown,pageId==='explorer'?values.sales:pageId==='trust'?values.rows:values.units)
 const onHand=detail.reduce((s,r)=>s+num(r,'on_hand'),0),target=detail.reduce((s,r)=>s+num(r,'target_stock'),0),avgDaily=detail.reduce((s,r)=>s+num(r,'avg_daily_demand'),0),risk=detail.filter(r=>String(r.risk_status).match(/Critical|Out of stock|Low stock/)).length,critical=detail.filter(r=>String(r.risk_status).match(/Critical|Out of stock/)).length
 const observed=values.units||0,baseline=forecast?.baseline??{},candidate=forecast?.candidate??{},baselineRmse=Number(baseline.rmse??0),candidateRmse=Number(candidate.rmse??0),winner=String(forecast?.selected_model??'moving_average_28d'),improvement=Number(forecast?.candidate_improvement??0),bias=Number((winner==='linear_trend'?candidate:biasOrBaseline(baseline)).bias??0),wape=Number((winner==='linear_trend'?candidate:baseline).wape??0)
 const recommendation=Math.max(0,Math.round(avgDaily*(lead+safety)*(scenario/100)-onHand)),checks=detail.filter(r=>'status'in r),failed=checks.filter(r=>String(r.status)!=='Passed').length,icons=[Target,BarChart3,Activity,Gauge,pageId==='trust'?DatabaseZap:FlaskConical]
 let content:ReactNode
 if(pageId==='forecast'){
  const views=[<><Stat value={winner.replaceAll('_',' ')}>{lang==='pt'?'modelo selecionado':'selected model'}</Stat><Stat value={pct(improvement)} tone={improvement>=.05?'positive':'negative'}>{lang==='pt'?'ganho do candidato':'candidate improvement'}</Stat><Stat value={String(forecast?.holdout_observations??0)}>{lang==='pt'?'observações de holdout':'holdout observations'}</Stat></>,<><Stat value={compact(winner==='linear_trend'?candidateRmse:baselineRmse,lang)}>RMSE</Stat><Stat value={wape?pct(wape):'—'}>WAPE</Stat><Stat value={compact(observed,lang)}>{lang==='pt'?'unidades observadas':'observed units'}</Stat></>,<><Stat value={bias?compact(Math.abs(bias),lang):'—'} tone={bias?'negative':undefined}>{bias>0?(lang==='pt'?'superestimação média':'average over-forecast'):bias<0?(lang==='pt'?'subestimação média':'average under-forecast'):(lang==='pt'?'viés indisponível':'bias unavailable')}</Stat><Stat value={baselineRmse?compact(baselineRmse,lang):'—'}>{lang==='pt'?'erro do baseline':'baseline error'}</Stat></>,<><Stat value={pct(stats.cv)}>{lang==='pt'?'variabilidade da demanda':'demand variability'}</Stat><Stat value={compact(stats.mean,lang)}>{lang==='pt'?'média diária':'daily average'}</Stat><Stat value={String(stats.points)}>{lang==='pt'?'dias visíveis':'visible days'}</Stat></>,<><label><span>{lang==='pt'?'Demanda':'Demand'} <b>{scenario}%</b></span><input type="range" min="70" max="140" value={scenario} onChange={e=>setScenario(Number(e.target.value))}/></label><Stat value={compact(observed*scenario/100,lang)}>{lang==='pt'?'unidades no cenário':'scenario units'}</Stat><Stat value={compact(observed*(scenario-100)/100,lang)} tone={scenario>=100?'positive':'negative'}>{lang==='pt'?'diferença linear':'linear difference'}</Stat></>]
  content=views[lens]
 }else if(pageId==='risk'){
  const views=[<><Stat value={String(critical)} tone={critical?'negative':undefined}>{lang==='pt'?'críticos visíveis':'visible critical'}</Stat><Stat value={String(risk)}>{lang==='pt'?'itens em risco visíveis':'visible at-risk items'}</Stat><Stat value={compact(values.reorder||0,lang)}>{lang==='pt'?'necessidade total do snapshot':'total snapshot need'}</Stat></>,<><Stat value={compact(Math.max(0,target-onHand),lang)}>{lang==='pt'?'gap visível até o alvo':'visible gap to target'}</Stat><Stat value={pct(target?onHand/target:0)}>{lang==='pt'?'cobertura do alvo':'target coverage'}</Stat><Stat value={compact(onHand,lang)}>{lang==='pt'?'estoque visível':'visible stock'}</Stat></>,<DriverList rows={drivers} lang={lang}/>,<><Stat value={pct(conc.top3Share)}>Top 3</Stat><Stat value={conc.leader?.name??'—'}>{lang==='pt'?'maior exposição de demanda':'largest demand exposure'}</Stat><Stat value={compact(values.units||0,lang)}>{lang==='pt'?'unidades no período':'period units'}</Stat></>,<><label><span>{lang==='pt'?'Demanda':'Demand'} <b>{scenario}%</b></span><input type="range" min="90" max="140" value={scenario} onChange={e=>setScenario(Number(e.target.value))}/></label><Stat value={compact(Math.max(0,avgDaily*12*scenario/100-onHand),lang)}>{lang==='pt'?'necessidade estressada visível':'visible stressed need'}</Stat><Stat value={compact(avgDaily,lang)}>{lang==='pt'?'demanda diária visível':'visible daily demand'}</Stat></>]
  content=views[lens]
 }else if(pageId==='explorer'){
  const leader=ranked[0],tail=ranked.at(-1),transfer=(leader?.value??0)*.1
  const views=[<><Stat value={leader?.name??'—'}>{lang==='pt'?'líder da rede':'network leader'}</Stat><Stat value={pct(values.sales?(leader?.value??0)/values.sales:0)}>{lang==='pt'?'participação do líder':'leader share'}</Stat><Stat value={compact(values.sales||0,lang)}>{lang==='pt'?'vendas do recorte':'scoped sales'}</Stat></>,<DriverList rows={drivers} lang={lang}/>,<><Stat value={leader&&tail?`${((leader.value/(tail.value||1))).toFixed(1)}×`:'—'}>{lang==='pt'?'líder versus cauda exibida':'leader versus displayed tail'}</Stat><Stat value={tail?.name??'—'}>{lang==='pt'?'menor grupo exibido':'smallest displayed group'}</Stat></>,<><Stat value={pct(conc.top3Share)}>Top 3</Stat><Stat value={String(breakdown.length)}>{lang==='pt'?'grupos exibidos':'displayed groups'}</Stat></>,<><Stat value={compact(transfer,lang)}>{lang==='pt'?'10% do líder para testar':'10% of leader to test'}</Stat><Stat value={compact((tail?.value??0)+transfer,lang)}>{lang==='pt'?'cauda após redistribuição':'tail after redistribution'}</Stat><Stat value="Scenario">{lang==='pt'?'não é previsão':'not a forecast'}</Stat></>]
  content=views[lens]
 }else if(pageId==='replenishment'){
  const views=[<><Stat value={compact(values.reorder||0,lang)}>{lang==='pt'?'unidades sugeridas no snapshot':'snapshot suggested units'}</Stat><Stat value={String(risk)}>{lang==='pt'?'posições visíveis em risco':'visible risk positions'}</Stat></>,<><label><span>{lang==='pt'?'Prazo':'Lead time'} <b>{lead}d</b></span><input type="range" min="1" max="30" value={lead} onChange={e=>setLead(Number(e.target.value))}/></label><Stat value={compact(avgDaily*lead,lang)}>{lang==='pt'?'demanda durante o prazo':'lead-time demand'}</Stat></>,<><label><span>{lang==='pt'?'Segurança':'Safety stock'} <b>{safety}d</b></span><input type="range" min="0" max="21" value={safety} onChange={e=>setSafety(Number(e.target.value))}/></label><Stat value={compact(avgDaily*safety,lang)}>{lang==='pt'?'buffer calculado':'calculated buffer'}</Stat></>,<><label><span>{lang==='pt'?'Demanda':'Demand'} <b>{scenario}%</b></span><input type="range" min="70" max="140" value={scenario} onChange={e=>setScenario(Number(e.target.value))}/></label><Stat value={compact(avgDaily*scenario/100,lang)}>{lang==='pt'?'demanda diária ajustada':'adjusted daily demand'}</Stat></>,<><Stat value={compact(recommendation,lang)}>{lang==='pt'?'reposição simulada visível':'visible simulated replenishment'}</Stat><Stat value={compact(onHand,lang)}>{lang==='pt'?'estoque visível':'visible stock'}</Stat><Stat value="Human review">{lang==='pt'?'antes de comprar':'before purchasing'}</Stat></>]
  content=views[lens]
 }else{
  const views=[<><Stat value={String(checks.length-failed)} tone={failed?'negative':'positive'}>{lang==='pt'?'testes aprovados':'checks passed'}</Stat><Stat value={String(failed)} tone={failed?'negative':undefined}>{lang==='pt'?'testes para revisar':'checks to review'}</Stat></>,<><Stat value={String(values.coverage||0)}>{lang==='pt'?'dias cobertos':'days covered'}</Stat><Stat value={compact(values.rows||0,lang)}>{lang==='pt'?'linhas consultadas':'rows queried'}</Stat></>,<><Stat value="sale_date × store × SKU">{lang==='pt'?'grão do mart':'mart grain'}</Stat><Stat value={compact(values.sku||0,lang)}>SKUs</Stat><Stat value={compact(values.stores||0,lang)}>{lang==='pt'?'lojas':'stores'}</Stat></>,<><Stat value={compact(values.sales||0,lang)}>{lang==='pt'?'vendas recalculadas':'recalculated sales'}</Stat><Stat value={compact(values.units||0,lang)}>{lang==='pt'?'unidades recalculadas':'recalculated units'}</Stat><Stat value="Scoped">{lang==='pt'?'consulta no navegador':'browser query'}</Stat></>,<><Stat value={failed===0&&values.rows>0?(lang==='pt'?'Qualificada':'Qualified'):(lang==='pt'?'Revisar':'Review')} tone={failed?'negative':'positive'}>{lang==='pt'?'prontidão da evidência':'evidence readiness'}</Stat><Stat value="No purchase order">{lang==='pt'?'limite decisório':'decision boundary'}</Stat></>]
  content=views[lens]
 }
 return <section className="ops-lab"><div className="ops-lab-head"><div><span>{lang==='pt'?'LABORATÓRIO DA PÁGINA · REGRAS EXPLÍCITAS':'PAGE LAB · EXPLICIT RULES'}</span><h2>{c.title[lang==='pt'?1:0]}</h2></div><div role="tablist">{c.tabs.map((tab,index)=>{const Icon=icons[index];return <button role="tab" aria-selected={lens===index} className={lens===index?'active':''} onClick={()=>setLens(index as Lens)} key={tab[0]}><Icon/>{tab[lang==='pt'?1:0]}</button>})}</div></div><div className="ops-lab-body"><div className="ops-copy"><b>{c.questions[lens][lang==='pt'?1:0]}</b><p>{lang==='pt'?'Calculado no recorte selecionado; cenários são sensibilidades, não previsões.':'Calculated within scope; scenarios are sensitivities, not forecasts.'}</p></div>{content}</div></section>
}

function biasOrBaseline(value:Record<string,number|string>){return value}
export function PageInsight({pageId,values,trend,breakdown,detail,forecast,lang}:{pageId:string;values:Record<string,number>;trend:SeriesPoint[];breakdown:BreakdownRow[];detail:Record<string,string|number>[];forecast?:ForecastEvaluation;lang:Lang}){if(pageId==='command')return <OpsCommand values={values} trend={trend} breakdown={breakdown} detail={detail} lang={lang}/>;return <PlanningPageLab pageId={pageId} values={values} trend={trend} breakdown={breakdown} detail={detail} forecast={forecast} lang={lang}/>}
